// AUTO-GENERATED by scripts/generate-nav.mjs from ../mkdocs.yml — do not edit by hand.
export interface NavLeaf {
  title: string;
  kind: "md" | "notebook";
  path: string;
  source: string;
}
export interface NavExternal {
  title: string;
  kind: "external";
  href: string;
}
export interface NavSection {
  title: string;
  kind: "section";
  children: NavNode[];
}
export type NavNode = NavLeaf | NavExternal | NavSection;

export const navTree: NavNode[] = [
  {
    "title": "Home",
    "kind": "md",
    "path": "/README",
    "source": "README.md"
  },
  {
    "title": "Architecture",
    "kind": "md",
    "path": "/ARCHITECTURE",
    "source": "ARCHITECTURE.md"
  },
  {
    "title": "Roadmap",
    "kind": "section",
    "children": [
      {
        "title": "Master Roadmap",
        "kind": "md",
        "path": "/moon/ROADMAP",
        "source": "moon/ROADMAP.md"
      },
      {
        "title": "Search",
        "kind": "md",
        "path": "/moon/roadmaps/search",
        "source": "moon/roadmaps/search.md"
      },
      {
        "title": "Core",
        "kind": "md",
        "path": "/moon/roadmaps/core",
        "source": "moon/roadmaps/core.md"
      },
      {
        "title": "CLI",
        "kind": "md",
        "path": "/moon/roadmaps/cli",
        "source": "moon/roadmaps/cli.md"
      },
      {
        "title": "Ingestion",
        "kind": "md",
        "path": "/moon/roadmaps/ingestion",
        "source": "moon/roadmaps/ingestion.md"
      }
    ]
  },
  {
    "title": "Changelog",
    "kind": "md",
    "path": "/CHANGELOG",
    "source": "CHANGELOG.md"
  },
  {
    "title": "Research",
    "kind": "section",
    "children": [
      {
        "title": "Building a Smart Recommendation Engine",
        "kind": "md",
        "path": "/research/Building a Smart Recommendation Engine",
        "source": "research/Building a Smart Recommendation Engine.md"
      }
    ]
  },
  {
    "title": "Image-Toolkit (parent project)",
    "kind": "external",
    "href": "https://github.com/ACFHarbinger/Image-Toolkit"
  }
];

export const searchIndex: { title: string; path: string; source: string; kind: "md" | "notebook" }[] = [
  {
    "title": "Home",
    "path": "/README",
    "source": "README.md",
    "kind": "md"
  },
  {
    "title": "Architecture",
    "path": "/ARCHITECTURE",
    "source": "ARCHITECTURE.md",
    "kind": "md"
  },
  {
    "title": "Master Roadmap",
    "path": "/moon/ROADMAP",
    "source": "moon/ROADMAP.md",
    "kind": "md"
  },
  {
    "title": "Search",
    "path": "/moon/roadmaps/search",
    "source": "moon/roadmaps/search.md",
    "kind": "md"
  },
  {
    "title": "Core",
    "path": "/moon/roadmaps/core",
    "source": "moon/roadmaps/core.md",
    "kind": "md"
  },
  {
    "title": "CLI",
    "path": "/moon/roadmaps/cli",
    "source": "moon/roadmaps/cli.md",
    "kind": "md"
  },
  {
    "title": "Ingestion",
    "path": "/moon/roadmaps/ingestion",
    "source": "moon/roadmaps/ingestion.md",
    "kind": "md"
  },
  {
    "title": "Changelog",
    "path": "/CHANGELOG",
    "source": "CHANGELOG.md",
    "kind": "md"
  },
  {
    "title": "Building a Smart Recommendation Engine",
    "path": "/research/Building a Smart Recommendation Engine",
    "source": "research/Building a Smart Recommendation Engine.md",
    "kind": "md"
  }
];
